### ISSUE TITLE
Bug: metadata tag to turn off `\cref`

### ISSUE THREAD

**Issue by crmackay** [bwhelm/pandoc-reference-filter#1]
on [line 669](https://github.com/bwhelm/pandoc-reference-filter/blob/master/internalreferences.py#L669)

the metadata data input string for `autoref` is never converted to a boolean value.

```python

metadata = doc[0]['unMeta']
args = {k: v['c'] for k, v in metadata.items()}
autoref = args.get('autoref', True)
numbersections = args.get('numbersections', True)

refmanager = ReferenceManager(autoref=autoref, numbersections=numbersections)
```

so when evaluated during instantiation of a `ReferenceManager` it always returns `True`

```python 

def __init__(self, autoref=True, numbersections=True):
        if autoref:
            self.replacements = {'figure': 'Figure {}',
                                 'section': 'Section {}',
                                 'table': 'Table {}',

```

**Comment by bwhelm** [comment]
I'm not sure I understand the issue. `autoref=True` is the default, so that references in the text will be to "Figure 1" or "Section 3.3", etc. However, if you set `autoref: false` in the YAML header, your references will just be numbers, not preceded by "Figure " or "Section ", etc. Doesn't that work for you?

**Comment by crmackay** [comment]
yeah...sorry, my metadata block wasn't formatted right, so it wan't being processed correcntly....apologies....

thanks for keeping this filter up-to-date btw!
